### ISSUE TITLE
Top bar buttons (Cards, etc.) not clickable

### ISSUE THREAD

**Issue by jamesmcm** [Annihil/revolut-emergency#1]
When I try to run the app via `npm start`, the buttons are the top are not clickable which makes it impossible to view the cards.

The JS console has no relevant output, and neither does yarn in the terminal.

The side-by-side account view button does work though.

**Comment by Annihil** [comment]
On what OS? Can you record a video please

**Comment by jamesmcm** [comment]
Arch Linux, on 2 installations too.

Let me try the snap, as if that works it might be an option to put that on the AUR.

I don't want to put a video here as it shows all the account details directly.

**Comment by jamesmcm** [comment]
Unfortunately the snap has the same issue, it's very strange.

Would it be possible to add hotkeys to switch between the top menu items (i.e. 1, 2 ,3) to at least mitigate the issue?

**Comment by Annihil** [comment]
The only thing I can think of is that
https://github.com/Annihil/revolut-emergency/blob/211a02c5d734b5c4d6d26a99bbde5173591f3a86/src/components/Navbar.tsx#L17
could you try removing this line and see if that helps?

**Comment by jamesmcm** [comment]
@Annihil that worked! Thanks!

Maybe check what effect the different webkit-app-region settings have on your build, to see if it's possible to change it without causing issues elsewhere.

**Comment by Jaifroid** [comment]
Using the Version 3.0 release from the Releases page, Windows 10, I am having the same issue. I cannot click on any of the icons in the top bar, i.e. none of the icons shown below, including the little cross, minimize and fullscreen icons.

![image](https://user-images.githubusercontent.com/4304337/69502938-85616c00-0f0c-11ea-9926-33aee6614d2d.png)

**Comment by Annihil** [comment]
It should be fixed by #2 😊

**Comment by bogdan-calapod** [comment]
Don't know if this is still active, but for what it's worth the window border is completely unusable on Windows 10 (nevermind the fact that for some reason the window controls are on the wrong side)
