### ISSUE TITLE
6 digit verification - Not applicable

### ISSUE THREAD

**Issue by eliac7** [Annihil/revolut-emergency#12]
It asks for a 6 digit verification but the e-mail asks to authenticate from the phone I am using and not from a desktop application.

![2020-04-28 14_58_52-R Emergency](https://user-images.githubusercontent.com/26083840/80484678-ca2c7b80-8960-11ea-90f8-73aee6ffdac7.png)

![2020-04-28-15_00_20-Netflix](https://user-images.githubusercontent.com/26083840/80485029-5fc80b00-8961-11ea-9510-d448e9be40ca.jpg)

**Comment by Annihil** [comment]
Click on the [[?]](https://github.com/Annihil/revolut-emergency/wiki/How-to-login-with-email) to see how to extract the 6 digits code from the email.

**Comment by eliac7** [comment]
> Click on the [[?]](https://github.com/Annihil/revolut-emergency/wiki/How-to-login-with-email) to see how to extract the 6 digits code from the email.

Oops, didn't know the wiki section on Github. Thanks for the clarification.

**Comment by eliac7** [comment]
> Click on the [[?]](https://github.com/Annihil/revolut-emergency/wiki/How-to-login-with-email) to see how to extract the 6 digits code from the email.

Oops, didn't know the wiki section on Github. Thanks for the clarification.
