### ISSUE TITLE
[Question] Which API?

### ISSUE THREAD

**Issue by Serpens66** [Annihil/revolut-emergency#4]
Hi, 
thank you for your work.

I'm no expert programmer, so I can not check your code.
But I'm interested in how it works. So you are using an API from revolut? Which one, is there a public documentation? Can everyone use it, or are you providing your personal API Key for this tool?

Since I can not check your application, I would try to build something like this on my own in python for personal use. Just need to know how the communication with revolut works.

**Comment by Annihil** [comment]
Hey,
Are you a programmer or are you not, since you mentioned being able to develop in python?
The API code is in ... `src/api.ts`! It's using the official revolut API, there is no documentation for it.
Cheers.

**Comment by Serpens66** [comment]
thanks, nowadays it is not as simple, I know basics of python and know APIs and how to connect to them. But that's basically all I know, so it is really hard for me to read and understand your code, also because I dont know the language you are using. 

So back to my question:
ok, in your code I see baseurl is "api.revolut.com". But when I google for revolut and API I find business API: https://developers.revolut.com/docs/#business-api and banking API https://developers.revolut.com/docs/#open-banking-api .
So, you aren't using one of them, but instead you are using an non public API, only ment to be used by the revolut app (and therefore the lack of documentation)? 
I just want to understand the API you are using and how authentication and so on works. I could easily write a python script for the business API documentation, but this is obviously not what you are using.
