### ISSUE TITLE
navigation buttons don't work on windows 10

### ISSUE THREAD

**Issue by rrrafalsz** [Annihil/revolut-emergency#5]
### bug report

**expected behaviour:** 
when i click on one of the navigation buttons (minimize, expand, close), a respective action should occur.

**current behaviour:**
when i click on the buttons, nothing happens.

**info:**
version: 3.2.0
system: windows 10
other: using the executable provided in the release information

**Comment by rrrafalsz** [comment]
PS. thanks for a great app!

**Comment by Annihil** [comment]
Hi, thank you for letting me know, I will investigate!

**Comment by Annihil** [comment]
Fixed
