### ISSUE TITLE
Biometric authentication

### ISSUE THREAD

**Issue by pdelw** [Annihil/revolut-emergency#8]
Hi,

When I'm trying to log in, after providing the email authentication code I get another screen which asks me to take a selfie (even though the account is already active and verified).

After clicking on "Take" button I just get error stating "Biometric authentication attempt has been rejected". 

Any idea if anything can be done in this situation?

Thank you

**Comment by Annihil** [comment]
Most likely your selfie has been rejected, the problem seems to be located between your keyboard and your chair.

**Comment by pdelw** [comment]
That would be right if I actually could take a selfie from the app - which I can't.

**Comment by Annihil** [comment]
U need some kind of webcam to take a selfie
